#!/usr/bin/env python3
"""One-attempt, zero-step updated-replay cache profiler for design202608146.

This runner is intentionally single-purpose.  It authenticates a separately
frozen execution protocol and every byte-bound input, atomically consumes the
one cache-profile attempt, and only then imports third-party code or executes
held repository source bytes.  It builds the deterministic train-only replay
cache and publishes its hashes; it never instantiates a model, performs a
forward/backward pass, constructs an optimizer, writes a checkpoint, or uses a
CUDA device.

The execution protocol is deliberately not generated by this file.  It must
be frozen separately after this runner's SHA-256 is known.
"""

from __future__ import annotations

import argparse
import ast
import copy
import fcntl
import hashlib
import json
import multiprocessing
import os
import re
import stat
import sys
import types
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence


sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"
SCRIPT = TOOLS / "audit_design202608146_updated_replay_cache_v1.py"
EXPECTED_PYTHON = Path("/home/xxc/miniconda3/envs/my_project_env/bin/python")

BRANCH = (
    "ppo_guardedu468_updatedreplay_g8_ppo4x96_u472_"
    "freshjointactor6_s8_design202608146"
)
SCHEMA = "ptcg-design202608146-updated-replay-cache-profile-result-v1"
PROTOCOL_SCHEMA = (
    "ptcg-design202608146-updated-replay-cache-profile-"
    "execution-preregistration-v1"
)
PROTOCOL_STATUS = "LOCKED_AFTER_RUNNER_AND_BEFORE_SINGLE_CACHE_PROFILE_ATTEMPT"

MASTER = ROOT / (
    "artifacts/ppo_guardedu468_updatedreplay_g8_ppo4x96_u472_"
    "freshjointactor6_s8_design202608146.cache_profile_master_preregistration.json"
)
MASTER_SHA256 = "e6f6e42a234b63757bdfd7004e814ef0f16e1ba31e4f11ce01192ed8132416bb"
PROTOCOL = ROOT / (
    "artifacts/ppo_guardedu468_updatedreplay_g8_ppo4x96_u472_"
    "freshjointactor6_s8_design202608146.cache_profile_execution_preregistration.json"
)
ATTEMPT = ROOT / ".ptcg-design202608146-updated-replay-cache-profile-attempt.json"
RESULT = ROOT / (
    "artifacts/ppo_guardedu468_updatedreplay_g8_ppo4x96_u472_"
    "freshjointactor6_s8_design202608146.updated_replay_cache_profile.json"
)

PUBLICATION_DIRECTORY_BINDINGS: dict[str, dict[str, Any]] = {
    "repository_root": {
        "path": ROOT,
        "device": 66310,
        "inode": 39604179,
        "mode": 0o775,
        "nlink": 14,
    },
    "artifacts": {
        "path": ROOT / "artifacts",
        "device": 66310,
        "inode": 39611154,
        "mode": 0o775,
        "nlink": 272,
    },
}

RECIPE_DRAFT = ROOT / (
    "artifacts/ppo_guardedu468_updatedreplay_g8_ppo4x96_u472_"
    "freshjointactor6_s8_design202608145.master_preregistration.draft.json"
)
STATIC_GAP = ROOT / (
    "artifacts/ppo_guardedu468_updatedreplay_g8_ppo4x96_u472_"
    "freshjointactor6_s8_design202608145.static_gap_report.json"
)
ATLAS_ATTEMPT = ROOT / (
    ".ptcg-ppo_u456_g8_guarded3x4x96_currentparent_"
    "cohortatlas_design202608144-attempt.json"
)
ATLAS_RESULT = ROOT / (
    "artifacts/ppo_u456_g8_guarded3x4x96_currentparent_"
    "cohortatlas_design202608144.atlas.json"
)
ATLAS_POSTMORTEM = ROOT / (
    "artifacts/ppo_u456_g8_guarded3x4x96_currentparent_"
    "cohortatlas_design202608144.execution_failure_postmortem.json"
)
LEDGER = ROOT / (
    "artifacts/official_unique_changed_candidate_ledger_"
    "before_cohortatlas_design202608144.json"
)
PARENT = ROOT / (
    "artifacts/ppo_u456_g8_guarded3x4x96_p12_design202608141/"
    "ppo_stage/block3/B_gold_league/seed-202608141/checkpoints/update-0468.pt"
)
PARENT_RUN_CONFIG = ROOT / (
    "artifacts/ppo_u456_g8_guarded3x4x96_p12_design202608141/"
    "ppo_stage/block3/B_gold_league/seed-202608141/run_config.json"
)
UPDATED_REPLAY = ROOT / (
    "data/bc_marnie_top50plus_gold21_timeforward_"
    "train28_valid29_v2_20260731.zip"
)
GENERAL_BC = ROOT / (
    "artifacts/bc_marnie_train28_valid29_gold21_orbit_v5_"
    "seed20260922_20260731/best.pt"
)
TRAIN_PPO = TOOLS / "train_ppo.py"
CACHE_HELPER = TOOLS / "run_ppo_bc_repair.py"
TRAIN_BC_ORBIT = TOOLS / "train_bc_orbit.py"

HEX64 = re.compile(r"^[0-9a-f]{64}$")
TRAIN_PREFIX = "train/"
FORBIDDEN_PREFIXES = ("valid/", "test/")
SELECTED_BATCH_INDICES = (1, 3, 4, 5, 6, 7, 8, 11)

# train_bc_orbit is the only additional repository source needed by the
# authenticated train_ppo cache builder.  It is not ordinary-imported: its
# exact held bytes are executed in a private module after the attempt marker.
STATIC_BINDINGS: dict[str, tuple[Path, str, int]] = {
    "master": (MASTER, MASTER_SHA256, 0o444),
    "recipe_draft": (
        RECIPE_DRAFT,
        "102f48f3fcba0a60b909ea3a87b27f0fb881eb399a60e78e3b1acf0db0a91583",
        0o644,
    ),
    "static_gap_report": (
        STATIC_GAP,
        "18de37fc62ab1b41c2d5d976b48ab36e3d07f1d77ad9ada30c0b835c288ef3cc",
        0o644,
    ),
    "closed_atlas_attempt": (
        ATLAS_ATTEMPT,
        "a9b5fe99f2bffb719d45fa6180349b6f76cd2bb43440fc0c35252a729512b37e",
        0o444,
    ),
    "closed_atlas_result": (
        ATLAS_RESULT,
        "34b1fd8e3f0eba0c501bda9b82c9415dadd021ff81a128f5166df15223493f5a",
        0o444,
    ),
    "atlas_postmortem": (
        ATLAS_POSTMORTEM,
        "55c03b6c78c23af711b19b637694f477a4aaca7ed2e3df56e35cdd20f2597646",
        0o444,
    ),
    "official_candidate_ledger": (
        LEDGER,
        "0b5d87b7f7bc3f794cdf4b8f386382e5287fe401629cb01ae2e5d162857e7fb3",
        0o444,
    ),
    "guarded_u468_parent": (
        PARENT,
        "a9290745b8eb58704c4617594ac5ab49500c6e65ecd9f273a8285c12547fbb83",
        0o444,
    ),
    "guarded_u468_run_config": (
        PARENT_RUN_CONFIG,
        "1de013a90d6ad6b05669d6da24bbcf36ead4a9c9c6cb8875713a16a8a6a2c867",
        0o444,
    ),
    "updated_general_replay": (
        UPDATED_REPLAY,
        "95638471e0b842c6366231e95b2e98a5d806f612a0085ef39110ba4cb6f0ad0d",
        0o664,
    ),
    "general_bc_anchor": (
        GENERAL_BC,
        "c75c7146cb4b48a20de3c5ca16ad98ddeec669eb2f803e2b6c6ab107b56154eb",
        0o664,
    ),
    "train_ppo": (
        TRAIN_PPO,
        "de3d1467d2b18a551b66c2e897e774d251a898b276dac709268b03d05da41ba3",
        0o664,
    ),
    "cache_hash_helper": (
        CACHE_HELPER,
        "6035e023c760dd23fb426a9b363cd59f4a8bf71e14534eb19c0a4e2e73aa9966",
        0o664,
    ),
    "train_bc_orbit_dependency": (
        TRAIN_BC_ORBIT,
        "ee68efc864511d2c88da0429aba8500611e9a2a5a1738573c8073a58cb73a9cc",
        0o664,
    ),
}

CACHE_CONTRACT: dict[str, Any] = {
    "split": "train",
    "seed": 202608145,
    "shuffle_seed": 202608186,
    "stratification_seed": 202608218,
    "batches": 72,
    "batch_size": 256,
    "rows": 18432,
    "workers": 8,
    "bc_replay_steps_for_cache_enablement_only": 2,
    "context34_rows_per_batch": 4,
    "context34_rows_total": 288,
    "selected_G8_batch_indices": list(SELECTED_BATCH_INDICES),
    "train_shards": 70,
}

CACHE_OVERRIDES: dict[str, Any] = {
    "bc_replay_data": str(UPDATED_REPLAY),
    "bc_replay_split": "train",
    "seed": 202608145,
    "bc_replay_batches": 72,
    "bc_replay_batch_size": 256,
    "bc_replay_workers": 8,
    "bc_replay_steps": 2,
    "bc_replay_context34_rows_per_batch": 4,
}

# The complete canonical config is checked in addition to the readable subset.
# This is the asdict(PPOConfig) stored by the exact guarded U468 run.
EXPECTED_PARENT_CONFIG_CANONICAL_SHA256 = (
    "94d4fe32ae3817f926c2d9117aa0ee9e11b0d8407982747a1bf6a11afe952b33"
)
EXPECTED_PARENT_CONFIG_SUBSET: dict[str, Any] = {
    "updates": 468,
    "environments": 16,
    "games_per_update": 96,
    "ppo_epochs": 2,
    "minibatch_size": 512,
    "learning_rate": 0.000024,
    "value_learning_rate": 0.0000075,
    "weight_decay": 0.0001,
    "max_grad_norm": 0.5,
    "policy_temperature": 0.8,
    "trainable_scope": "last_block_heads",
    "actor_reduction": "episode_mean",
    "bc_checkpoint": str(GENERAL_BC),
    "kl_reference_checkpoint": str(GENERAL_BC),
    "bc_replay_data": str(
        ROOT / "data/bc_marnie_top50_rollforward_test25_hash80_seed20260921.zip"
    ),
    "bc_replay_split": "train",
    "bc_replay_batches": 72,
    "bc_replay_batch_size": 256,
    "bc_replay_workers": 8,
    "bc_replay_steps": 2,
    "bc_replay_lr_scale": 0.075,
    "bc_replay_loss": "ordered",
    "bc_replay_order_context_weight": 8.0,
    "bc_replay_context34_rows_per_batch": 4,
    "bc_replay_non_context34_fixed_multi_action_order_weight": 1.0,
    "seed": 202608141,
    "device": "cuda",
}
EXPECTED_MODEL_CONFIG: dict[str, Any] = {
    "hash_size": 65536,
    "categorical_dim": 64,
    "model_dim": 128,
    "layers": 4,
    "heads": 4,
    "dropout": 0.05,
    "max_state_entities": 80,
    "entity_fields": 20,
    "option_fields": 24,
}
EXPECTED_TORCH_VERSION = "2.8.0+cu128"
EXPECTED_ORJSON_VERSION = "3.11.9"
EXPECTED_NUMPY_VERSION = "2.2.6"


class ProtocolError(RuntimeError):
    """Fail-closed contract error."""


class EngineSentinel:
    """A non-engine placeholder; any accidental engine access is fatal."""

    accesses = 0

    def __getattr__(self, name: str) -> Any:
        type(self).accesses += 1
        raise ProtocolError(f"cache profiler attempted engine access: {name}")


def canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
        + "\n"
    ).encode("utf-8")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def aggregate_batch_sha256(batch_sha256: Sequence[str]) -> str:
    digest = hashlib.sha256()
    for index, batch_hash in enumerate(batch_sha256):
        if not HEX64.fullmatch(batch_hash):
            raise ProtocolError("malformed batch SHA-256 in aggregate reconstruction")
        digest.update(str(index).encode("ascii"))
        digest.update(b"\0")
        digest.update(bytes.fromhex(batch_hash))
    return digest.hexdigest()


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def relative(path: Path) -> str:
    return str(path.relative_to(ROOT))


def strict_json_bytes(payload: bytes, label: str) -> dict[str, Any]:
    def reject_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise ProtocolError(f"{label} has duplicate JSON key {key!r}")
            result[key] = value
        return result

    try:
        value = json.loads(payload, object_pairs_hook=reject_duplicates)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ProtocolError(f"{label} is not strict UTF-8 JSON") from error
    if not isinstance(value, dict):
        raise ProtocolError(f"{label} root must be an object")
    return value


def sha256_fd(fd: int) -> str:
    observed = os.fstat(fd)
    digest = hashlib.sha256()
    offset = 0
    while offset < observed.st_size:
        chunk = os.pread(fd, min(1024 * 1024, observed.st_size - offset), offset)
        if not chunk:
            raise ProtocolError("short read while hashing held input")
        digest.update(chunk)
        offset += len(chunk)
    if offset != observed.st_size:
        raise ProtocolError("held input size changed while hashing")
    return digest.hexdigest()


def read_fd_bytes(fd: int) -> bytes:
    observed = os.fstat(fd)
    chunks: list[bytes] = []
    offset = 0
    while offset < observed.st_size:
        chunk = os.pread(fd, min(1024 * 1024, observed.st_size - offset), offset)
        if not chunk:
            raise ProtocolError("short read from held input")
        chunks.append(chunk)
        offset += len(chunk)
    result = b"".join(chunks)
    if len(result) != observed.st_size:
        raise ProtocolError("held input byte count drift")
    return result


def open_locked_input(
    label: str,
    path: Path,
    expected_sha256: str | None,
    expected_mode: int,
) -> dict[str, Any]:
    flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(path, flags)
    try:
        fcntl.flock(fd, fcntl.LOCK_SH | fcntl.LOCK_NB)
        observed = os.fstat(fd)
        if not stat.S_ISREG(observed.st_mode):
            raise ProtocolError(f"{label} must be a regular file")
        if observed.st_nlink != 1:
            raise ProtocolError(f"{label} must have exactly one hard link")
        mode = stat.S_IMODE(observed.st_mode)
        if mode != expected_mode:
            raise ProtocolError(
                f"{label} mode drift: expected {expected_mode:04o}, got {mode:04o}"
            )
        digest = sha256_fd(fd)
        if expected_sha256 is not None and digest != expected_sha256:
            raise ProtocolError(f"{label} SHA-256 drift")
        return {
            "label": label,
            "path": path,
            "fd": fd,
            "sha256": digest,
            "mode": mode,
            "device": observed.st_dev,
            "inode": observed.st_ino,
            "size": observed.st_size,
            "mtime_ns": observed.st_mtime_ns,
            "nlink": observed.st_nlink,
        }
    except BaseException:
        os.close(fd)
        raise


def public_evidence(snapshot: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "path": relative(Path(snapshot["path"])),
        "sha256": snapshot["sha256"],
        "mode_octal": f"{int(snapshot['mode']):04o}",
        "bytes": int(snapshot["size"]),
        "device": int(snapshot["device"]),
        "inode": int(snapshot["inode"]),
        "nlink": int(snapshot["nlink"]),
    }


def assert_snapshot_unchanged(snapshot: Mapping[str, Any]) -> None:
    held = os.fstat(int(snapshot["fd"]))
    path = Path(snapshot["path"])
    visible = os.lstat(path)
    identity = (
        int(snapshot["device"]),
        int(snapshot["inode"]),
        int(snapshot["size"]),
        int(snapshot["mtime_ns"]),
        int(snapshot["mode"]),
        int(snapshot["nlink"]),
    )
    held_identity = (
        held.st_dev,
        held.st_ino,
        held.st_size,
        held.st_mtime_ns,
        stat.S_IMODE(held.st_mode),
        held.st_nlink,
    )
    visible_identity = (
        visible.st_dev,
        visible.st_ino,
        visible.st_size,
        visible.st_mtime_ns,
        stat.S_IMODE(visible.st_mode),
        visible.st_nlink,
    )
    if identity != held_identity or identity != visible_identity:
        raise ProtocolError(f"held input identity changed: {snapshot['label']}")
    if sha256_fd(int(snapshot["fd"])) != snapshot["sha256"]:
        raise ProtocolError(f"held input bytes changed: {snapshot['label']}")
    flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    visible_fd = os.open(path, flags)
    try:
        fcntl.flock(visible_fd, fcntl.LOCK_SH | fcntl.LOCK_NB)
        reopened = os.fstat(visible_fd)
        reopened_identity = (
            reopened.st_dev,
            reopened.st_ino,
            reopened.st_size,
            reopened.st_mtime_ns,
            stat.S_IMODE(reopened.st_mode),
            reopened.st_nlink,
        )
        if reopened_identity != identity:
            raise ProtocolError(
                f"visible input changed while reopening: {snapshot['label']}"
            )
        if sha256_fd(visible_fd) != snapshot["sha256"]:
            raise ProtocolError(f"visible input bytes changed: {snapshot['label']}")
    finally:
        try:
            fcntl.flock(visible_fd, fcntl.LOCK_UN)
        finally:
            os.close(visible_fd)


def release_snapshots(snapshots: Mapping[str, Mapping[str, Any]]) -> None:
    for snapshot in reversed(list(snapshots.values())):
        fd = int(snapshot["fd"])
        try:
            fcntl.flock(fd, fcntl.LOCK_UN)
        finally:
            os.close(fd)


def binding(path: Path, digest: str, mode: int) -> dict[str, Any]:
    observed = os.lstat(path)
    if (
        not stat.S_ISREG(observed.st_mode)
        or stat.S_IMODE(observed.st_mode) != mode
        or observed.st_nlink != 1
    ):
        raise ProtocolError(f"protocol binding stat drift: {relative(path)}")
    return {
        "path": relative(path),
        "sha256": digest,
        "mode_octal": f"{mode:04o}",
        "bytes": int(observed.st_size),
        "device": int(observed.st_dev),
        "inode": int(observed.st_ino),
        "mtime_ns": int(observed.st_mtime_ns),
        "nlink": int(observed.st_nlink),
    }


def expected_protocol(self_sha256: str) -> dict[str, Any]:
    bindings = {
        "runner": binding(SCRIPT, self_sha256, 0o555),
        **{
            label: binding(path, digest, mode)
            for label, (path, digest, mode) in STATIC_BINDINGS.items()
        },
    }
    return {
        "schema_version": PROTOCOL_SCHEMA,
        "status": PROTOCOL_STATUS,
        "branch": BRANCH,
        "bindings": bindings,
        "invocation": {
            "runtime_python": str(EXPECTED_PYTHON),
            "required_python_flags": ["-I", "-B"],
            "runner": str(SCRIPT),
            "protocol": str(PROTOCOL),
            "argv_template": [
                str(EXPECTED_PYTHON),
                "-I",
                "-B",
                str(SCRIPT),
                "--protocol",
                str(PROTOCOL),
                "--expected-protocol-sha256",
                "<EXPECTED_PROTOCOL_SHA256>",
            ],
            "expected_protocol_sha256_is_only_supplied_by_argv": True,
        },
        "cache_contract": CACHE_CONTRACT,
        "publication_lock": {
            "directories": {
                label: {
                    "path": relative(item["path"]),
                    "device": int(item["device"]),
                    "inode": int(item["inode"]),
                    "mode_octal": f"{int(item['mode']):04o}",
                    "nlink": int(item["nlink"]),
                    "held_lock": "LOCK_SH|LOCK_NB",
                }
                for label, item in PUBLICATION_DIRECTORY_BINDINGS.items()
            },
            "attempt": {"path": relative(ATTEMPT), "absent_at_lock": True},
            "result": {"path": relative(RESULT), "absent_at_lock": True},
            "O_EXCL_is_authoritative_race_gate": True,
        },
        "implementation_closure": {
            "third_party_and_repository_imports_after_attempt_only": True,
            "train_bc_orbit_held_byte_exec": True,
            "train_ppo_held_byte_exec": True,
            "cache_hash_helper_held_byte_exec": True,
            "ordinary_repo_imports": [],
            "cg_engine_replaced_by_fatal_sentinel": True,
            "cache_hash_helper_only_external_call": "replay_cache_manifest",
            "cuda_visible_devices": "",
            "parent_checkpoint_deserialized": False,
            "guarded_u468_run_config_is_separate_hash_bound_input": True,
            "mutable_archive_transport": "/proc/self/fd/<held_archive_fd>",
            "dataloader_workers_explicitly_shutdown": True,
            "terminal_held_and_visible_identity_and_sha256_recheck": True,
            "numpy_version": EXPECTED_NUMPY_VERSION,
            "byteorder": "little",
            "zero_step_runtime_tripwires": True,
            "terminal_cuda_is_initialized_false": True,
            "cache_tensors_CPU_and_no_grad": True,
        },
        "stop_rules": {
            "attempts_authorized": 1,
            "retry_authorized": False,
            "attempt_marker_precedes_third_party_or_repository_import": True,
            "any_post_attempt_failure_closes_design202608146": True,
            "existing_attempt_or_result_is_fatal": True,
            "result_is_O_EXCL_then_mode_0444": True,
            "attempt_and_result_absent_at_directory_lock_and_claim": True,
            "root_and_artifacts_directory_identity_held_until_terminal_publication": True,
            "runner_held_stat_identity_and_sha256_rechecked_terminally": True,
            "publication_fd_readback_and_directory_fsync": True,
        },
        "scope": {
            "train_only": True,
            "validation": False,
            "test": False,
            "gold_payload_or_score": False,
            "network": False,
            "optimizer_steps": 0,
            "model_instances": 0,
            "model_forwards": 0,
            "checkpoint_writes": 0,
            "changed_candidates_constructed_or_evaluated": 0,
            "package_upload_submission": False,
        },
    }


def proc_cmdline() -> list[str]:
    payload = Path("/proc/self/cmdline").read_bytes()
    return [os.fsdecode(token) for token in payload.rstrip(b"\0").split(b"\0")]


def validate_runtime_and_argv(args: argparse.Namespace) -> dict[str, Any]:
    if Path.cwd().resolve() != ROOT:
        raise ProtocolError("current working directory must be the repository root")
    if Path(sys.executable).resolve() != EXPECTED_PYTHON.resolve():
        raise ProtocolError("runner must use my_project_env Python")
    if sys.flags.isolated != 1 or sys.flags.dont_write_bytecode != 1:
        raise ProtocolError("runner requires exact Python flags -I -B")
    if args.protocol.resolve() != PROTOCOL:
        raise ProtocolError("--protocol path is not the exact frozen target")
    if not HEX64.fullmatch(args.expected_protocol_sha256):
        raise ProtocolError("--expected-protocol-sha256 must be lowercase SHA-256")
    expected_argv = [
        str(EXPECTED_PYTHON),
        "-I",
        "-B",
        str(SCRIPT),
        "--protocol",
        str(PROTOCOL),
        "--expected-protocol-sha256",
        args.expected_protocol_sha256,
    ]
    observed_argv = proc_cmdline()
    if observed_argv != expected_argv:
        raise ProtocolError("process argv differs from the exact frozen invocation")
    return {
        "python": str(EXPECTED_PYTHON),
        "python_resolved": str(EXPECTED_PYTHON.resolve()),
        "version": sys.version.split()[0],
        "isolated": True,
        "dont_write_bytecode": True,
        "argv": observed_argv,
    }


def target_absent(directory_fd: int, leaf: str) -> bool:
    try:
        os.stat(leaf, dir_fd=directory_fd, follow_symlinks=False)
    except FileNotFoundError:
        return True
    return False


def open_locked_directory(
    label: str, path: Path, expected: Mapping[str, Any]
) -> dict[str, Any]:
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(path, flags)
    try:
        fcntl.flock(fd, fcntl.LOCK_SH | fcntl.LOCK_NB)
        held = os.fstat(fd)
        visible = os.lstat(path)
        if not stat.S_ISDIR(held.st_mode) or not stat.S_ISDIR(visible.st_mode):
            raise ProtocolError(f"{label} publication directory is not a directory")
        held_identity = (
            held.st_dev,
            held.st_ino,
            stat.S_IMODE(held.st_mode),
            held.st_nlink,
        )
        visible_identity = (
            visible.st_dev,
            visible.st_ino,
            stat.S_IMODE(visible.st_mode),
            visible.st_nlink,
        )
        expected_identity = (
            int(expected["device"]),
            int(expected["inode"]),
            int(expected["mode"]),
            int(expected["nlink"]),
        )
        if held_identity != expected_identity or visible_identity != expected_identity:
            raise ProtocolError(f"{label} publication directory identity drift")
        return {
            "label": label,
            "path": path,
            "fd": fd,
            "device": held.st_dev,
            "inode": held.st_ino,
            "mode": stat.S_IMODE(held.st_mode),
            "nlink": held.st_nlink,
        }
    except BaseException:
        os.close(fd)
        raise


def assert_directory_unchanged(snapshot: Mapping[str, Any]) -> None:
    held = os.fstat(int(snapshot["fd"]))
    visible = os.lstat(Path(snapshot["path"]))
    identity = (
        int(snapshot["device"]),
        int(snapshot["inode"]),
        int(snapshot["mode"]),
        int(snapshot["nlink"]),
    )
    if (
        not stat.S_ISDIR(held.st_mode)
        or not stat.S_ISDIR(visible.st_mode)
        or (
            held.st_dev,
            held.st_ino,
            stat.S_IMODE(held.st_mode),
            held.st_nlink,
        )
        != identity
        or (
            visible.st_dev,
            visible.st_ino,
            stat.S_IMODE(visible.st_mode),
            visible.st_nlink,
        )
        != identity
    ):
        raise ProtocolError(
            f"publication directory changed: {snapshot['label']}"
        )


def directory_evidence(snapshot: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "path": relative(Path(snapshot["path"])),
        "device": int(snapshot["device"]),
        "inode": int(snapshot["inode"]),
        "mode_octal": f"{int(snapshot['mode']):04o}",
        "nlink": int(snapshot["nlink"]),
        "held_shared_lock": True,
    }


def release_directory(snapshot: Mapping[str, Any]) -> None:
    fd = int(snapshot["fd"])
    try:
        fcntl.flock(fd, fcntl.LOCK_UN)
    finally:
        os.close(fd)


def publish_exclusive(
    directory_fd: int,
    leaf: str,
    payload: Mapping[str, Any],
    relative_path: Path,
) -> dict[str, Any]:
    if Path(leaf).name != leaf or leaf in {"", ".", ".."}:
        raise ProtocolError("publication leaf is invalid")
    raw = canonical_json_bytes(payload)
    flags = os.O_RDWR | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(leaf, flags, 0o600, dir_fd=directory_fd)
    try:
        offset = 0
        while offset < len(raw):
            written = os.write(fd, raw[offset:])
            if written <= 0:
                raise ProtocolError("short exclusive publication write")
            offset += written
        os.fsync(fd)
        os.fchmod(fd, 0o444)
        os.fsync(fd)
        observed = os.fstat(fd)
        if (
            not stat.S_ISREG(observed.st_mode)
            or stat.S_IMODE(observed.st_mode) != 0o444
            or observed.st_nlink != 1
            or observed.st_size != len(raw)
        ):
            raise ProtocolError("immutable publication shape drift")
        if sha256_fd(fd) != sha256_bytes(raw):
            raise ProtocolError("immutable publication held-fd readback drift")
        os.fsync(directory_fd)
    finally:
        os.close(fd)
    return {
        "path": relative(relative_path),
        "sha256": sha256_bytes(raw),
        "mode_octal": "0444",
        "bytes": len(raw),
    }


def dotted_name(node: ast.AST) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        parent = dotted_name(node.value)
        return f"{parent}.{node.attr}" if parent else node.attr
    return None


def static_source_audit(source: bytes) -> dict[str, Any]:
    tree = ast.parse(source, filename=str(SCRIPT))
    imports: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imports.add(node.module.split(".")[0])
    forbidden_imports = {
        "torch",
        "orjson",
        "train_ppo",
        "train_bc_orbit",
        "run_ppo_bc_repair",
        "subprocess",
        "socket",
        "requests",
        "urllib",
        "http",
        "ftplib",
    }
    bad_imports = sorted(imports & forbidden_imports)
    call_names = {
        name
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        for name in [dotted_name(node.func)]
        if name is not None
    }
    forbidden_calls = sorted(
        name
        for name in call_names
        if name in {
            "subprocess.run",
            "subprocess.Popen",
            "torch.cuda.is_available",
            "torch.cuda.manual_seed_all",
            "torch.optim.AdamW",
            "torch.load",
        }
        or name.endswith(".backward")
        or name.endswith(".model_forward")
        or "instantiate_model" in name
    )
    required_functions = {
        "expected_protocol",
        "validate_master_and_lineage",
        "validate_protocol",
        "run_cache_profile",
        "publish_exclusive",
        "sanitized_failure",
        "main",
    }
    observed_functions = {
        node.name for node in tree.body if isinstance(node, ast.FunctionDef)
    }
    main_guards = [
        node
        for node in tree.body
        if isinstance(node, ast.If)
        and isinstance(node.test, ast.Compare)
        and isinstance(node.test.left, ast.Name)
        and node.test.left.id == "__name__"
        and len(node.test.ops) == 1
        and isinstance(node.test.ops[0], ast.Eq)
        and len(node.test.comparators) == 1
        and isinstance(node.test.comparators[0], ast.Constant)
        and node.test.comparators[0].value == "__main__"
    ]
    checks = {
        "no_third_party_or_repo_static_imports": not bad_imports,
        "no_forbidden_training_cuda_or_network_calls": not forbidden_calls,
        "required_control_functions_present": required_functions <= observed_functions,
        "single_main_guard": len(main_guards) == 1,
    }
    if not all(checks.values()):
        raise ProtocolError(
            f"runner static source audit failed: imports={bad_imports}, "
            f"calls={forbidden_calls}, checks={checks}"
        )
    return {
        "checks": checks,
        "top_level_import_roots": sorted(imports),
        "forbidden_imports_observed": bad_imports,
        "forbidden_calls_observed": forbidden_calls,
    }


def validate_master_and_lineage(
    master: Mapping[str, Any], snapshots: Mapping[str, Mapping[str, Any]]
) -> dict[str, Any]:
    checks = {
        "schema": master.get("schema_version")
        == (
            "ptcg-guardedu468-updatedreplay-g8-ppo4x96-u472-"
            "freshjointactor6-s8-design202608146-cache-profile-master-v1"
        ),
        "status": master.get("status")
        == "LOCKED_FOR_DEDICATED_ZERO_STEP_CACHE_PROFILER_IMPLEMENTATION_AND_STATIC_AUDIT_ONLY",
        "branch": master.get("branch") == BRANCH,
        "training_seed": master.get("training_seed") == 202608145,
        "runner": master.get("cache_profile", {}).get("runner_path")
        == relative(SCRIPT),
        "attempt": master.get("cache_profile", {}).get("attempt_marker")
        == relative(ATTEMPT),
        "result": master.get("cache_profile", {}).get("result")
        == relative(RESULT),
        "cache_contract": all(
            master.get("cache_profile", {}).get(key) == value
            for key, value in CACHE_CONTRACT.items()
            if key != "train_shards"
        ),
        "identity_manifest_deferred": master.get("cache_profile", {}).get(
            "identity_manifest_for_future_S8"
        )
        == (
            "not_authorized_or_required_in_this_G8_cache_profile; "
            "U472 train-only profile must reconstruct and freeze identities "
            "separately before S8"
        ),
        "implementation_authorized": master.get("authorization", {}).get(
            "dedicated_cache_profiler_implementation_and_static_audit_authorized"
        )
        is True,
        "execution_not_authorized_by_master": master.get("authorization", {}).get(
            "cache_profile_execution_authorized_now"
        )
        is False,
        "separate_protocol_required": master.get("authorization", {}).get(
            "separate_frozen_execution_preregistration_required"
        )
        is True,
        "zero_optimizer": master.get("authorization", {}).get(
            "optimizer_steps_authorized"
        )
        == 0,
        "no_candidate": master.get("authorization", {}).get("candidate_authorized")
        is False,
    }
    master_bindings = {
        "recipe_draft": master.get("lineage", {}).get("recipe_draft", {}),
        "static_gap_report": master.get("lineage", {}).get("static_gap_report", {}),
        "closed_atlas_attempt": master.get("lineage", {}).get(
            "closed_atlas_attempt", {}
        ),
        "closed_atlas_result": master.get("lineage", {}).get(
            "closed_atlas_result", {}
        ),
        "atlas_postmortem": master.get("lineage", {}).get("atlas_postmortem", {}),
        "official_candidate_ledger": master.get("official_candidate_ledger", {}),
        "guarded_u468_parent": master.get("bound_inputs", {}).get(
            "guarded_u468_parent", {}
        ),
        "updated_general_replay": master.get("bound_inputs", {}).get(
            "updated_general_replay", {}
        ),
        "general_bc_anchor": master.get("bound_inputs", {}).get(
            "general_bc_anchor", {}
        ),
        "train_ppo": master.get("bound_inputs", {}).get("train_ppo", {}),
        "cache_hash_helper": master.get("bound_inputs", {}).get(
            "cache_hash_helper", {}
        ),
    }
    for label, item in master_bindings.items():
        expected_path, expected_digest, _ = STATIC_BINDINGS[label]
        digest_key = "file_sha256" if "file_sha256" in item else "sha256"
        checks[f"master_binding_{label}"] = (
            item.get("path") == relative(expected_path)
            and item.get(digest_key) == expected_digest
            and snapshots[label]["sha256"] == expected_digest
        )

    recipe = strict_json_bytes(
        read_fd_bytes(int(snapshots["recipe_draft"]["fd"])), "recipe draft"
    )
    gap = strict_json_bytes(
        read_fd_bytes(int(snapshots["static_gap_report"]["fd"])), "static gap"
    )
    atlas = strict_json_bytes(
        read_fd_bytes(int(snapshots["closed_atlas_result"]["fd"])), "atlas result"
    )
    postmortem = strict_json_bytes(
        read_fd_bytes(int(snapshots["atlas_postmortem"]["fd"])), "atlas postmortem"
    )
    ledger = strict_json_bytes(
        read_fd_bytes(int(snapshots["official_candidate_ledger"]["fd"])),
        "candidate ledger",
    )
    checks.update(
        {
            "recipe_still_non_executable": recipe.get("status")
            == "DRAFT_NON_EXECUTABLE_UNFROZEN",
            "gap_still_no_go": gap.get("status") == "NO_GO_DRAFT_NOT_EXECUTABLE",
            "atlas_attempt_consumed_failure": atlas.get("status")
            == "ATLAS_EXECUTION_FAILED_ATTEMPT_CONSUMED",
            "atlas_closed_no_retry": postmortem.get("status")
            == "CLOSED_NO_RETRY_ACTOR_DIGEST_LITERAL_TYPO_BEFORE_PARENT_FORWARD",
            "separate_route_eligible": postmortem.get("route_decision", {}).get(
                "separate_updated_replay_general_bc_ppo_fresh_joint_special_bc_route_remains_eligible"
            )
            is True,
            "separate_route_needs_own_freeze": postmortem.get(
                "route_decision", {}
            ).get("separate_route_requires_its_own_frozen_executable_preregistration")
            is True,
            "ledger_budget": ledger.get("budget") == 12,
            "ledger_consumed": ledger.get("consumed_before_atlas") == 2,
            "ledger_remaining": ledger.get("remaining_before_atlas") == 10,
            "ledger_atlas_consumed_zero": ledger.get("atlas_branch_consumes") == 0,
        }
    )
    if not all(checks.values()):
        failed = sorted(key for key, value in checks.items() if not value)
        raise ProtocolError(f"master or lineage semantic drift: {failed}")
    return {"checks": checks}


def validate_protocol(
    protocol: Mapping[str, Any], self_sha256: str
) -> dict[str, Any]:
    expected = expected_protocol(self_sha256)
    if protocol != expected:
        raise ProtocolError("execution protocol differs from exact runner contract")
    return {
        "schema_version": PROTOCOL_SCHEMA,
        "status": PROTOCOL_STATUS,
        "exact_object_match": True,
        "runner_sha256": self_sha256,
    }


def archive_train_manifest(archive_fd: int, archive_sha256: str) -> dict[str, Any]:
    duplicate = os.dup(archive_fd)
    try:
        with os.fdopen(duplicate, "rb", closefd=True) as handle:
            duplicate = -1
            with zipfile.ZipFile(handle) as archive:
                infos = archive.infolist()
    finally:
        if duplicate >= 0:
            os.close(duplicate)
    names = [info.filename for info in infos]
    if len(names) != len(set(names)):
        raise ProtocolError("updated replay ZIP has duplicate central-directory names")
    entries: list[dict[str, Any]] = []
    forbidden_member_count = 0
    for central_index, info in enumerate(infos):
        name = info.filename
        if name.startswith(FORBIDDEN_PREFIXES):
            forbidden_member_count += 1
        if not (name.startswith(TRAIN_PREFIX) and name.endswith(".jsonl")):
            continue
        pure = Path(name)
        if pure.is_absolute() or ".." in pure.parts or info.is_dir():
            raise ProtocolError("irregular train member path in updated replay ZIP")
        unix_mode = (int(info.external_attr) >> 16) & 0xFFFF
        if unix_mode and stat.S_ISLNK(unix_mode):
            raise ProtocolError("symlink train member in updated replay ZIP")
        entries.append(
            {
                "train_index": len(entries),
                "central_index": central_index,
                "name": name,
                "crc32_hex": f"{int(info.CRC):08x}",
                "compress_type": int(info.compress_type),
                "flag_bits": int(info.flag_bits),
                "compressed_bytes": int(info.compress_size),
                "uncompressed_bytes": int(info.file_size),
            }
        )
    if len(entries) != 70:
        raise ProtocolError(f"updated replay train shard count is {len(entries)}, not 70")
    expected_names = [f"train/part-{index:05d}.jsonl" for index in range(70)]
    if [entry["name"] for entry in entries] != expected_names:
        raise ProtocolError(
            "updated replay train members are not exact ordered part-00000..00069"
        )
    if any(int(entry["flag_bits"]) & 0x1 for entry in entries):
        raise ProtocolError("updated replay contains encrypted train member")
    core = {
        "schema_version": "ptcg-design202608146-train-zip-central-directory-v1",
        "archive_sha256": archive_sha256,
        "selector": "central-directory order where name starts train/ and ends .jsonl",
        "exact_expected_names": expected_names,
        "train_member_count": len(entries),
        "compressed_bytes_total": sum(
            int(entry["compressed_bytes"]) for entry in entries
        ),
        "uncompressed_bytes_total": sum(
            int(entry["uncompressed_bytes"]) for entry in entries
        ),
        "entries": entries,
    }
    manifest_sha256 = sha256_bytes(canonical_json_bytes(core))
    return {
        "definition": (
            "canonical JSON of train/*.jsonl central-directory entries in exact "
            "central-directory order, including train/central indices, name, "
            "CRC, flag bits, compression type, and compressed/uncompressed sizes"
        ),
        "sha256": manifest_sha256,
        "canonical_core": core,
        "train_member_count": len(entries),
        "forbidden_prefix_member_count_in_inventory_only": forbidden_member_count,
        "archive_member_payloads_opened_for_inventory": 0,
        "entries": entries,
    }


def exec_held_module(name: str, source: bytes, canonical_path: Path) -> types.ModuleType:
    module = types.ModuleType(name)
    module.__file__ = str(canonical_path)
    module.__cached__ = None
    module.__loader__ = None
    module.__package__ = None
    module.__spec__ = None
    sys.modules[name] = module
    try:
        exec(compile(source, str(canonical_path), "exec"), module.__dict__)
    except BaseException:
        sys.modules.pop(name, None)
        raise
    return module


def repo_modules() -> dict[str, str]:
    result: dict[str, str] = {}
    for name, module in list(sys.modules.items()):
        raw = getattr(module, "__file__", None)
        if not isinstance(raw, str):
            continue
        try:
            path = Path(raw).resolve()
            path.relative_to(ROOT)
        except (OSError, ValueError):
            continue
        result[name] = str(path)
    return result


def load_authenticated_stack(
    snapshots: Mapping[str, Mapping[str, Any]],
) -> tuple[dict[str, Any], dict[str, Any]]:
    for name in ("train_bc_orbit", "train_ppo", "cg", "cg.sim"):
        if name in sys.modules:
            raise ProtocolError(f"repository import closure contaminated before load: {name}")
    path_before = list(sys.path)
    repo_before = repo_modules()
    modules_added: list[str] = []
    try:
        bc_source = read_fd_bytes(int(snapshots["train_bc_orbit_dependency"]["fd"]))
        ppo_source = read_fd_bytes(int(snapshots["train_ppo"]["fd"]))
        helper_source = read_fd_bytes(int(snapshots["cache_hash_helper"]["fd"]))

        bc = exec_held_module("train_bc_orbit", bc_source, TRAIN_BC_ORBIT)
        modules_added.append("train_bc_orbit")

        cg = types.ModuleType("cg")
        cg.__path__ = []
        sim = types.ModuleType("cg.sim")
        sim.lib = EngineSentinel()
        cg.sim = sim
        sys.modules["cg"] = cg
        sys.modules["cg.sim"] = sim
        modules_added.extend(["cg", "cg.sim"])

        ppo = exec_held_module("train_ppo", ppo_source, TRAIN_PPO)
        modules_added.append("train_ppo")
        helper_name = "_design202608146_cache_hash_helper"
        helper = exec_held_module(helper_name, helper_source, CACHE_HELPER)
        modules_added.append(helper_name)

        checks = {
            "ppo_dataset_is_held_bc_dataset": ppo.ZipDecisionDataset
            is bc.ZipDecisionDataset,
            "ppo_collator_is_held_bc_collator": ppo.collate_decisions
            is bc.collate_decisions,
            "helper_uses_held_ppo_module": helper.ppo is ppo,
            "cache_builder_callable": callable(ppo.build_bc_replay_batches),
            "cache_manifest_callable": callable(helper.replay_cache_manifest),
            "engine_sentinel_not_accessed_during_import": EngineSentinel.accesses == 0,
        }
        repo_after = repo_modules()
        permitted = {
            "train_bc_orbit": str(TRAIN_BC_ORBIT),
            "train_ppo": str(TRAIN_PPO),
            helper_name: str(CACHE_HELPER),
        }
        unexpected = {
            name: path
            for name, path in repo_after.items()
            if name not in repo_before and permitted.get(name) != path
        }
        checks["no_unbound_repository_module_loaded"] = not unexpected
        sys.path[:] = path_before
        checks["sys_path_restored_immediately_after_held_load"] = (
            sys.path == path_before
        )
        if not all(checks.values()):
            raise ProtocolError(
                f"authenticated implementation closure failed: {checks}, "
                f"unexpected={unexpected}"
            )
        return (
            {"bc": bc, "ppo": ppo, "helper": helper, "modules_added": modules_added},
            {
                "checks": checks,
                "held_sources": {
                    "train_bc_orbit": public_evidence(
                        snapshots["train_bc_orbit_dependency"]
                    ),
                    "train_ppo": public_evidence(snapshots["train_ppo"]),
                    "cache_hash_helper": public_evidence(
                        snapshots["cache_hash_helper"]
                    ),
                },
                "unexpected_repo_modules": unexpected,
                "sys_path_restored_immediately_after_held_load": True,
                "path_before": path_before,
                "repo_before": repo_before,
                "permitted_repo_modules": permitted,
            },
        )
    except BaseException:
        sys.path[:] = path_before
        for name in reversed(modules_added):
            sys.modules.pop(name, None)
        raise


def cleanup_authenticated_stack(
    stack: Mapping[str, Any], closure: Mapping[str, Any]
) -> dict[str, Any]:
    sys.path[:] = list(closure["path_before"])
    for name in reversed(list(stack["modules_added"])):
        sys.modules.pop(name, None)
    remaining = {
        name: path
        for name, path in repo_modules().items()
        if name in set(stack["modules_added"])
    }
    return {
        "private_modules_removed": not remaining,
        "remaining_private_repo_modules": remaining,
        "sys_path_restored": sys.path == list(closure["path_before"]),
    }


def validate_parent_and_clone_config(
    run_config: Mapping[str, Any], ppo: Any
) -> tuple[Any, dict[str, Any], dict[str, Any]]:
    raw_config = run_config.get("config")
    model_config = run_config.get("model_config")
    if not isinstance(raw_config, dict) or not isinstance(model_config, dict):
        raise ProtocolError("guarded U468 run_config lacks config/model_config")
    expected_config_fields = set(ppo.PPOConfig.__dataclass_fields__)
    if set(raw_config) != expected_config_fields:
        raise ProtocolError("guarded parent PPOConfig field set drift")
    canonical_config_sha = sha256_bytes(canonical_json_bytes(raw_config))
    if canonical_config_sha != EXPECTED_PARENT_CONFIG_CANONICAL_SHA256:
        raise ProtocolError("guarded parent complete config hash drift")
    subset_checks = {
        key: raw_config.get(key) == expected
        for key, expected in EXPECTED_PARENT_CONFIG_SUBSET.items()
    }
    if not all(subset_checks.values()):
        failed = sorted(key for key, value in subset_checks.items() if not value)
        raise ProtocolError(f"guarded parent config subset drift: {failed}")
    if model_config != EXPECTED_MODEL_CONFIG:
        raise ProtocolError("guarded parent model_config drift")

    cloned = copy.deepcopy(raw_config)
    before = copy.deepcopy(cloned)
    for key, value in CACHE_OVERRIDES.items():
        cloned[key] = value
    changed = sorted(key for key in cloned if cloned[key] != before[key])
    if changed != ["bc_replay_data", "seed"]:
        raise ProtocolError(f"cache config changed unexpected fields: {changed}")
    if any(cloned.get(key) != value for key, value in CACHE_OVERRIDES.items()):
        raise ProtocolError("cache config override drift")
    config = ppo.PPOConfig(**cloned)
    audit = {
        "parent_update": 468,
        "parent_complete_config_canonical_sha256": canonical_config_sha,
        "parent_config_field_count": len(raw_config),
        "parent_config_subset_checks": subset_checks,
        "parent_model_config": model_config,
        "parent_checkpoint_deserialized": False,
        "parent_checkpoint_identity_source": "frozen_file_SHA256_only",
        "run_config_identity_source": "separately_hash_bound_immutable_JSON",
        "clone_override_assignments": CACHE_OVERRIDES,
        "fields_with_changed_values": changed,
        "all_other_config_fields_bitwise_JSON_equal": all(
            key in CACHE_OVERRIDES or cloned[key] == before[key] for key in before
        ),
        "cache_config_canonical_sha256": sha256_bytes(canonical_json_bytes(cloned)),
    }
    return config, copy.deepcopy(model_config), audit


def install_runtime_tripwires(torch: Any, stack: Mapping[str, Any]) -> dict[str, Any]:
    counters = {
        "checkpoint_load": 0,
        "checkpoint_save": 0,
        "model_init": 0,
        "model_forward": 0,
        "optimizer_init": 0,
        "optimizer_step": 0,
        "backward": 0,
        "cuda_lazy_init": 0,
        "bc_replay_update": 0,
    }
    originals: list[tuple[Any, str, Any]] = []

    def replace(target: Any, attribute: str, counter: str) -> None:
        if not hasattr(target, attribute):
            raise ProtocolError(f"runtime tripwire target absent: {attribute}")
        original = getattr(target, attribute)

        def denied(*positional: Any, **keyword: Any) -> Any:
            del positional, keyword
            counters[counter] += 1
            raise ProtocolError(f"forbidden zero-step operation attempted: {counter}")

        originals.append((target, attribute, original))
        setattr(target, attribute, denied)

    ppo = stack["ppo"]
    bc = stack["bc"]
    replace(torch, "load", "checkpoint_load")
    replace(torch, "save", "checkpoint_save")
    replace(torch.optim.Optimizer, "__init__", "optimizer_init")
    replace(torch.optim.Optimizer, "step", "optimizer_step")
    replace(torch.autograd, "backward", "backward")
    replace(torch.cuda, "_lazy_init", "cuda_lazy_init")
    replace(bc.EntityOptionPolicy, "__init__", "model_init")
    replace(bc.EntityOptionPolicy, "forward", "model_forward")
    replace(ppo, "model_forward", "model_forward")
    replace(ppo, "instantiate_model_from_bc", "model_init")
    replace(ppo, "instantiate_model_from_checkpoint", "model_init")
    replace(ppo, "bc_replay_update", "bc_replay_update")
    replace(ppo, "save_ppo_checkpoint", "checkpoint_save")
    return {"counters": counters, "originals": originals}


def restore_runtime_tripwires(state: Mapping[str, Any]) -> dict[str, int]:
    for target, attribute, original in reversed(list(state["originals"])):
        setattr(target, attribute, original)
    return {key: int(value) for key, value in state["counters"].items()}


def run_cache_profile(
    snapshots: Mapping[str, Mapping[str, Any]],
) -> dict[str, Any]:
    # This occurs after the immutable attempt marker.  No third-party module is
    # imported before this point.  Hiding every CUDA device before importing
    # torch ensures the cache-only process cannot acquire a CUDA device.
    os.environ["CUDA_VISIBLE_DEVICES"] = ""
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
    torch = __import__("torch")
    orjson = __import__("orjson")
    numpy = __import__("numpy")
    if str(torch.__version__) != EXPECTED_TORCH_VERSION:
        raise ProtocolError(f"torch version drift: {torch.__version__}")
    if str(orjson.__version__) != EXPECTED_ORJSON_VERSION:
        raise ProtocolError(f"orjson version drift: {orjson.__version__}")
    if str(numpy.__version__) != EXPECTED_NUMPY_VERSION:
        raise ProtocolError(f"numpy version drift: {numpy.__version__}")
    if sys.byteorder != "little":
        raise ProtocolError(f"byte order drift: {sys.byteorder}")
    if bool(torch.cuda.is_initialized()):
        raise ProtocolError("CUDA was initialized before cache construction")

    stack: dict[str, Any] = {}
    closure: dict[str, Any] = {}
    cleanup: dict[str, Any] | None = None
    tripwires: dict[str, Any] | None = None
    try:
        stack, closure = load_authenticated_stack(snapshots)
        ppo = stack["ppo"]
        helper = stack["helper"]
        tripwires = install_runtime_tripwires(torch, stack)

        frozen_run_config = strict_json_bytes(
            read_fd_bytes(int(snapshots["guarded_u468_run_config"]["fd"])),
            "guarded U468 run_config",
        )
        config, model_config, parent_audit = validate_parent_and_clone_config(
            frozen_run_config, ppo
        )

        # The semantic clone is frozen against the repository archive path.
        # The actual cache read is transported through the already-held archive
        # descriptor so the mutable mode-0664 pathname cannot be swapped or
        # modified between authentication and DataLoader worker opens.
        archive_snapshot = snapshots["updated_general_replay"]
        archive_transport_path = f"/proc/self/fd/{int(archive_snapshot['fd'])}"
        transport_stat = os.stat(archive_transport_path)
        if (
            transport_stat.st_dev != int(archive_snapshot["device"])
            or transport_stat.st_ino != int(archive_snapshot["inode"])
            or transport_stat.st_size != int(archive_snapshot["size"])
        ):
            raise ProtocolError("held archive /proc descriptor identity drift")
        transport_config = copy.deepcopy(config)
        transport_config.bc_replay_data = archive_transport_path

        archive_manifest = archive_train_manifest(
            int(snapshots["updated_general_replay"]["fd"]),
            str(snapshots["updated_general_replay"]["sha256"]),
        )
        train_names = [entry["name"] for entry in archive_manifest["entries"]]
        train_index = {name: index for index, name in enumerate(train_names)}
        if len(train_index) != 70:
            raise ProtocolError("train member manifest identity collision")

        context = multiprocessing.get_context()
        start_method = context.get_start_method()
        if start_method != "fork":
            raise ProtocolError(
                f"cache profiler requires inherited fork guards, got {start_method}"
            )
        opened_bits = context.Array("b", len(train_names), lock=True)
        opened_calls = context.Value("Q", 0, lock=True)
        original_zip_open = zipfile.ZipFile.open
        original_loader = ppo.DataLoader
        loader_audits: list[dict[str, Any]] = []
        loader_proxies: list[Any] = []

        class GuardedLoaderProxy:
            def __init__(self, loader: Any) -> None:
                self.loader = loader
                self.iterator: Any | None = None
                self.explicit_shutdown_called = False
                self.workers: list[Any] = []
                self.worker_pids: list[int] = []
                self.worker_exitcodes_after_shutdown: dict[int, int] = {}
                self.workers_alive_after_shutdown: list[int] = []

            def __iter__(self) -> Any:
                if self.iterator is not None:
                    raise ProtocolError("guarded DataLoader iterated more than once")
                self.iterator = iter(self.loader)
                workers = list(getattr(self.iterator, "_workers", ()))
                self.workers = workers
                self.worker_pids = [
                    int(worker.pid) for worker in workers if worker.pid is not None
                ]
                if len(self.worker_pids) != 8 or len(set(self.worker_pids)) != 8:
                    raise ProtocolError("DataLoader did not start 8 distinct workers")
                return self.iterator

            def shutdown_workers(self) -> None:
                if self.iterator is None:
                    return
                shutdown = getattr(self.iterator, "_shutdown_workers", None)
                if not callable(shutdown):
                    raise ProtocolError("DataLoader iterator lacks explicit shutdown hook")
                shutdown()
                self.explicit_shutdown_called = True
                self.workers_alive_after_shutdown = [
                    int(worker.pid)
                    for worker in self.workers
                    if worker.pid is not None and worker.is_alive()
                ]
                if self.workers_alive_after_shutdown:
                    raise ProtocolError("DataLoader workers remained alive after shutdown")
                if any(worker.pid is None or worker.exitcode is None for worker in self.workers):
                    raise ProtocolError("DataLoader worker exit code unavailable")
                self.worker_exitcodes_after_shutdown = {
                    int(worker.pid): int(worker.exitcode) for worker in self.workers
                }
                if any(
                    exitcode != 0
                    for exitcode in self.worker_exitcodes_after_shutdown.values()
                ):
                    raise ProtocolError("DataLoader worker exited nonzero")

        def guarded_zip_open(
            archive: zipfile.ZipFile,
            name: Any,
            mode: str = "r",
            *positional: Any,
            **keyword: Any,
        ) -> Any:
            member = name.filename if isinstance(name, zipfile.ZipInfo) else str(name)
            if mode != "r" or not member.startswith(TRAIN_PREFIX):
                raise ProtocolError("cache builder attempted non-train ZIP member access")
            if member not in train_index:
                raise ProtocolError("cache builder attempted unmanifested train member")
            with opened_calls.get_lock():
                opened_calls.value += 1
            with opened_bits.get_lock():
                opened_bits[train_index[member]] = 1
            return original_zip_open(archive, name, mode, *positional, **keyword)

        def guarded_loader(*positional: Any, **keyword: Any) -> Any:
            dataset = positional[0] if positional else keyword.get("dataset")
            observed = {
                "num_workers": int(keyword.get("num_workers", -1)),
                "batch_size": int(keyword.get("batch_size", -1)),
                "dataset_type": type(dataset).__name__,
                "archive_path": str(getattr(dataset, "archive_path", "")),
                "split": getattr(dataset, "split", None),
                "max_rows": getattr(dataset, "max_rows", None),
                "split_seed": getattr(dataset, "split_seed", None),
                "shuffle_seed": getattr(dataset, "shuffle_seed", None),
                "epoch": getattr(dataset, "epoch", None),
                "split_mode": getattr(dataset, "split_mode", None),
                "shuffle_buffer_rows": getattr(dataset, "shuffle_buffer_rows", None),
                "use_trajectory_weights": getattr(
                    dataset, "use_trajectory_weights", None
                ),
            }
            expected = {
                "num_workers": 8,
                "batch_size": 256,
                "dataset_type": "ZipDecisionDataset",
                "archive_path": archive_transport_path,
                "split": "train",
                "max_rows": 18432,
                "split_seed": 202608145,
                "shuffle_seed": 202608186,
                "epoch": 0,
                "split_mode": "archive",
                "shuffle_buffer_rows": 0,
                "use_trajectory_weights": False,
            }
            observed["exact"] = all(
                observed.get(key) == value for key, value in expected.items()
            )
            if observed["exact"] is not True:
                raise ProtocolError(f"DataLoader/cache dataset contract drift: {observed}")
            loader_audits.append(observed)
            proxy = GuardedLoaderProxy(original_loader(*positional, **keyword))
            loader_proxies.append(proxy)
            return proxy

        zipfile.ZipFile.open = guarded_zip_open
        ppo.DataLoader = guarded_loader
        try:
            replay_batches = ppo.build_bc_replay_batches(
                transport_config, model_config
            )
        finally:
            try:
                for proxy in loader_proxies:
                    proxy.shutdown_workers()
            finally:
                ppo.DataLoader = original_loader
                zipfile.ZipFile.open = original_zip_open

        if len(loader_audits) != 1 or loader_audits[0].get("exact") is not True:
            raise ProtocolError("cache builder did not create exactly one guarded loader")
        if (
            len(loader_proxies) != 1
            or loader_proxies[0].iterator is None
            or loader_proxies[0].explicit_shutdown_called is not True
            or loader_proxies[0].workers_alive_after_shutdown
            or len(loader_proxies[0].worker_pids) != 8
            or len(set(loader_proxies[0].worker_pids)) != 8
            or len(loader_proxies[0].worker_exitcodes_after_shutdown) != 8
            or any(
                exitcode != 0
                for exitcode in loader_proxies[0].worker_exitcodes_after_shutdown.values()
            )
        ):
            raise ProtocolError("DataLoader worker lifecycle audit failed")
        loader_audits[0]["worker_pids_started_count"] = len(
            loader_proxies[0].worker_pids
        )
        loader_audits[0]["worker_pids_distinct"] = True
        loader_audits[0]["worker_exitcodes_after_shutdown"] = {
            str(pid): exitcode
            for pid, exitcode in sorted(
                loader_proxies[0].worker_exitcodes_after_shutdown.items()
            )
        }
        loader_audits[0]["explicit_worker_shutdown_called"] = True
        loader_audits[0]["workers_alive_after_shutdown"] = 0
        if len(replay_batches) != 72:
            raise ProtocolError("cache builder did not produce exactly 72 batches")

        aggregate_sha256, batch_sha256 = helper.replay_cache_manifest(replay_batches)
        if len(batch_sha256) != 72 or any(not HEX64.fullmatch(x) for x in batch_sha256):
            raise ProtocolError("cache hash helper returned malformed batch hashes")
        independent_aggregate_sha256 = aggregate_batch_sha256(batch_sha256)
        if independent_aggregate_sha256 != aggregate_sha256:
            raise ProtocolError("cache aggregate hash independent reconstruction drift")
        per_batch_rows = [
            int(batch["action_counts"].shape[0]) for batch in replay_batches
        ]
        per_batch_context34 = [
            int((batch["contexts"] == ppo.SKILL_ORDER_CONTEXT).sum())
            for batch in replay_batches
        ]
        if per_batch_rows != [256] * 72:
            raise ProtocolError("cache contains a short or oversized batch")
        if per_batch_context34 != [4] * 72:
            raise ProtocolError("cache context34 stratification drift")
        expected_tensor_keys = {
            "global_fields",
            "global_field_mask",
            "global_numeric",
            "state_fields",
            "state_field_mask",
            "state_numeric",
            "state_mask",
            "option_fields",
            "option_field_mask",
            "option_numeric",
            "option_mask",
            "targets",
            "action_counts",
            "action_sequences",
            "min_counts",
            "max_counts",
            "contexts",
            "sample_weights",
            "win_targets",
        }
        if any(set(batch) != expected_tensor_keys for batch in replay_batches):
            raise ProtocolError("cache tensor key set drift")
        if not all(
            isinstance(value, torch.Tensor)
            for batch in replay_batches
            for value in batch.values()
        ):
            raise ProtocolError("cache contains a non-tensor value")
        all_tensors_cpu_no_grad = all(
            value.device.type == "cpu" and value.requires_grad is False
            for batch in replay_batches
            for value in batch.values()
        )
        if not all_tensors_cpu_no_grad:
            raise ProtocolError("cache tensor escaped CPU or requires gradients")
        if not all(
            bool(torch.isfinite(value).all())
            for batch in replay_batches
            for value in batch.values()
            if value.is_floating_point()
        ):
            raise ProtocolError("cache contains non-finite floating tensors")

        selected_sha256 = [batch_sha256[index] for index in SELECTED_BATCH_INDICES]
        opened_indices = [
            index for index, value in enumerate(list(opened_bits)) if int(value) == 1
        ]
        if int(opened_calls.value) <= 0 or not opened_indices:
            raise ProtocolError("guarded cache builder recorded no train member reads")
        terminal_repo_modules = repo_modules()
        unexpected_runtime_repo_modules = {
            name: path
            for name, path in terminal_repo_modules.items()
            if name not in closure["repo_before"]
            and closure["permitted_repo_modules"].get(name) != path
        }
        if unexpected_runtime_repo_modules:
            raise ProtocolError(
                "cache runtime lazily loaded unbound repository module"
            )
        if sys.path != list(closure["path_before"]):
            raise ProtocolError("cache runtime changed sys.path after held load")
        closure["checks"]["no_unbound_repository_lazy_load_during_cache"] = True
        closure["checks"]["sys_path_unchanged_during_cache"] = True
        closure["unexpected_repo_modules_terminal"] = unexpected_runtime_repo_modules
        tripwire_counters = {
            key: int(value) for key, value in tripwires["counters"].items()
        }
        if any(tripwire_counters.values()):
            raise ProtocolError("zero-step runtime tripwire counter is nonzero")
        cuda_initialized_terminal = bool(torch.cuda.is_initialized())
        if cuda_initialized_terminal:
            raise ProtocolError("CUDA initialized during cache construction")

        output = {
            "runtime": {
                "python": str(EXPECTED_PYTHON),
                "python_version": sys.version.split()[0],
                "torch_version": str(torch.__version__),
                "orjson_version": str(orjson.__version__),
                "numpy_version": str(numpy.__version__),
                "byteorder": sys.byteorder,
                "CUDA_VISIBLE_DEVICES": os.environ.get("CUDA_VISIBLE_DEVICES"),
                "cuda_state_queries_by_runner": 2,
                "cuda_is_initialized_terminal": cuda_initialized_terminal,
                "cuda_devices_acquired": 0,
                "multiprocessing_start_method": start_method,
            },
            "zero_step_runtime_tripwires": {
                "armed_before_cache_construction": True,
                "counters": tripwire_counters,
                "all_counters_zero": not any(tripwire_counters.values()),
            },
            "authenticated_implementation_closure": {
                key: value
                for key, value in closure.items()
                if key
                not in {"path_before", "repo_before", "permitted_repo_modules"}
            },
            "parent_and_clone_audit": parent_audit,
            "held_archive_transport": {
                "semantic_config_path": str(UPDATED_REPLAY),
                "runtime_transport": "/proc/self/fd/<held_archive_fd>",
                "transport_targets_exact_held_device_inode_size": True,
                "path_based_mode0664_TOCTOU_closed": True,
                "DataLoader_workers_inherit_guard_and_held_fd": True,
            },
            "archive_train_member_manifest": archive_manifest,
            "guarded_member_access": {
                "ZipFile_open_rejected_every_non_train_or_unmanifested_member": True,
                "train_member_open_calls": int(opened_calls.value),
                "opened_train_member_indices": opened_indices,
                "opened_train_member_names": [train_names[index] for index in opened_indices],
                "non_train_member_payloads_opened": 0,
            },
            "loader_audit": loader_audits[0],
            "cache": {
                "aggregate_cache_sha256": aggregate_sha256,
                "independently_recomputed_aggregate_cache_sha256": (
                    independent_aggregate_sha256
                ),
                "all_72_batch_sha256_in_index_order": batch_sha256,
                "selected_G8_batch_indices": list(SELECTED_BATCH_INDICES),
                "selected_8_batch_sha256_in_frozen_index_order": selected_sha256,
                "per_batch_row_count": per_batch_rows,
                "per_batch_context34_count": per_batch_context34,
                "rows_total": sum(per_batch_rows),
                "context34_rows_total": sum(per_batch_context34),
                "archive_train_member_manifest_sha256": archive_manifest["sha256"],
            },
            "integrity": {
                "batches_exact72": len(replay_batches) == 72,
                "rows_exact72x256": sum(per_batch_rows) == 18432,
                "every_batch_rows_exact256": per_batch_rows == [256] * 72,
                "every_batch_context34_exact4": per_batch_context34 == [4] * 72,
                "context34_total_exact288": sum(per_batch_context34) == 288,
                "selected_indices_exact_and_distinct": (
                    tuple(SELECTED_BATCH_INDICES) == (1, 3, 4, 5, 6, 7, 8, 11)
                    and len(set(SELECTED_BATCH_INDICES)) == 8
                ),
                "all_hashes_well_formed": HEX64.fullmatch(aggregate_sha256)
                is not None
                and all(HEX64.fullmatch(value) for value in batch_sha256),
                "aggregate_hash_independently_recomputed": (
                    independent_aggregate_sha256 == aggregate_sha256
                ),
                "all_cache_floats_finite": True,
                "all_cache_tensors_CPU_and_no_grad": all_tensors_cpu_no_grad,
                "cuda_never_initialized": not cuda_initialized_terminal,
                "zero_step_tripwires_all_zero": not any(
                    tripwire_counters.values()
                ),
                "parent_checkpoint_never_deserialized": True,
                "parent_checkpoint_held_file_unchanged_until_terminal_recheck": True,
                "engine_accesses_zero": EngineSentinel.accesses == 0,
            },
            "scope_audit": {
                "optimizer_instances": 0,
                "optimizer_steps": 0,
                "model_instances": 0,
                "model_forwards": 0,
                "backward_calls": 0,
                "checkpoint_writes": 0,
                "changed_candidates_constructed_or_evaluated": 0,
                "identity_manifest_constructed": False,
                "validation_test_gold_payload_or_score_rows_opened": 0,
                "network": False,
                "package_upload_submission": False,
            },
        }
        if not all(output["integrity"].values()):
            raise ProtocolError("terminal cache integrity gate failed")
        return output
    finally:
        try:
            if tripwires is not None:
                restore_runtime_tripwires(tripwires)
        finally:
            if stack and closure:
                cleanup = cleanup_authenticated_stack(stack, closure)
        if cleanup is not None and not all(
            value for key, value in cleanup.items() if key != "remaining_private_repo_modules"
        ):
            raise ProtocolError(f"authenticated module cleanup failed: {cleanup}")


def sanitized_failure(
    error: BaseException,
    phase: str,
    attempt_evidence: Mapping[str, Any],
    protocol_sha256: str,
    runner_sha256: str,
    inputs_unchanged: bool,
) -> dict[str, Any]:
    message = str(error).encode("utf-8", errors="replace")
    return {
        "schema_version": SCHEMA,
        "status": "CACHE_PROFILE_FAILED_ATTEMPT_CONSUMED_DESIGN202608146_CLOSED_NO_RETRY",
        "branch": BRANCH,
        "completed_at_utc": utc_now(),
        "phase": phase,
        "failure": {
            "exception_class": type(error).__name__,
            "message_utf8_bytes": len(message),
            "message_sha256": sha256_bytes(message),
            "raw_message_published": False,
        },
        "attempt": dict(attempt_evidence),
        "protocol_sha256": protocol_sha256,
        "runner_sha256": runner_sha256,
        "inputs_unchanged_at_failure_check": inputs_unchanged,
        "decision": {
            "retry_authorized": False,
            "design202608146_closed": True,
            "G8_PPO_profile_S8_authorized": False,
        },
        "scope_audit": {
            "optimizer_steps": 0,
            "model_instances": 0,
            "model_forwards": 0,
            "checkpoint_writes": 0,
            "changed_candidates_constructed_or_evaluated": 0,
            "validation_test_gold_network_package_upload_submission": False,
        },
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protocol", type=Path, required=True)
    parser.add_argument("--expected-protocol-sha256", required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    runtime = validate_runtime_and_argv(args)
    root_directory = open_locked_directory(
        "repository_root", ROOT, PUBLICATION_DIRECTORY_BINDINGS["repository_root"]
    )
    try:
        artifacts_directory = open_locked_directory(
            "artifacts",
            ROOT / "artifacts",
            PUBLICATION_DIRECTORY_BINDINGS["artifacts"],
        )
    except BaseException:
        release_directory(root_directory)
        raise
    root_fd = int(root_directory["fd"])
    artifacts_fd = int(artifacts_directory["fd"])
    snapshots: dict[str, dict[str, Any]] = {}
    attempt_evidence: dict[str, Any] | None = None
    phase = "pre_attempt_control_plane"
    try:
        if not target_absent(root_fd, ATTEMPT.name):
            raise FileExistsError(f"attempt target already exists: {relative(ATTEMPT)}")
        if not target_absent(artifacts_fd, RESULT.name):
            raise FileExistsError(f"result target already exists: {relative(RESULT)}")

        snapshots["runner"] = open_locked_input("runner", SCRIPT, None, 0o555)
        snapshots["protocol"] = open_locked_input(
            "execution_protocol", PROTOCOL, args.expected_protocol_sha256, 0o444
        )
        for label, (path, digest, mode) in STATIC_BINDINGS.items():
            snapshots[label] = open_locked_input(label, path, digest, mode)

        runner_source = read_fd_bytes(int(snapshots["runner"]["fd"]))
        static_audit = static_source_audit(runner_source)
        master = strict_json_bytes(
            read_fd_bytes(int(snapshots["master"]["fd"])), "cache profile master"
        )
        protocol = strict_json_bytes(
            read_fd_bytes(int(snapshots["protocol"]["fd"])),
            "cache profile execution protocol",
        )
        lineage_audit = validate_master_and_lineage(master, snapshots)
        protocol_audit = validate_protocol(protocol, snapshots["runner"]["sha256"])
        for snapshot in snapshots.values():
            assert_snapshot_unchanged(snapshot)

        # Recheck a common absent-target instant immediately before the atomic
        # attempt claim.  The O_EXCL open remains the authoritative race gate.
        if not (
            target_absent(root_fd, ATTEMPT.name)
            and target_absent(artifacts_fd, RESULT.name)
        ):
            raise FileExistsError("publication target appeared before attempt claim")
        attempt_payload = {
            "schema_version": f"{SCHEMA}-attempt-v1",
            "status": "CACHE_PROFILE_ATTEMPT_CONSUMED_BEFORE_ANY_THIRD_PARTY_OR_REPO_IMPORT",
            "branch": BRANCH,
            "attempt": 1,
            "attempts_authorized": 1,
            "started_at_utc": utc_now(),
            "runner_sha256": snapshots["runner"]["sha256"],
            "protocol_sha256": snapshots["protocol"]["sha256"],
            "master_sha256": snapshots["master"]["sha256"],
            "input_sha256": {
                label: snapshot["sha256"]
                for label, snapshot in snapshots.items()
                if label not in {"runner", "protocol"}
            },
            "runtime": runtime,
            "static_source_audit": static_audit,
            "master_and_lineage_audit": lineage_audit,
            "protocol_audit": protocol_audit,
            "targets_absent_at_claim": {
                "attempt": True,
                "result": True,
            },
            "publication_directories_held_from_absence_check": {
                "repository_root": directory_evidence(root_directory),
                "artifacts": directory_evidence(artifacts_directory),
            },
            "runner_held_identity_at_claim": public_evidence(snapshots["runner"]),
            "third_party_or_repository_modules_imported_before_claim": 0,
            "optimizer_steps": 0,
            "changed_candidates_constructed_or_evaluated": 0,
            "retry_authorized": False,
        }
        attempt_evidence = publish_exclusive(
            root_fd, ATTEMPT.name, attempt_payload, ATTEMPT
        )

        phase = "post_attempt_authenticated_cache_construction"
        profile = run_cache_profile(snapshots)
        phase = "post_cache_input_identity_recheck"
        for snapshot in snapshots.values():
            assert_snapshot_unchanged(snapshot)
        assert_directory_unchanged(root_directory)
        assert_directory_unchanged(artifacts_directory)
        phase = "success_result_publication"
        result = {
            "schema_version": SCHEMA,
            "status": "CACHE_PROFILE_COMPLETED_ZERO_STEP_TRAIN_ONLY",
            "branch": BRANCH,
            "completed_at_utc": utc_now(),
            "attempt": attempt_evidence,
            "protocol": public_evidence(snapshots["protocol"]),
            "runner": public_evidence(snapshots["runner"]),
            "master": public_evidence(snapshots["master"]),
            "bindings": {
                label: public_evidence(snapshot)
                for label, snapshot in snapshots.items()
                if label not in {"runner", "protocol", "master"}
            },
            "static_source_audit": static_audit,
            "master_and_lineage_audit": lineage_audit,
            "protocol_audit": protocol_audit,
            **profile,
            "terminal_decision": {
                "cache_profile_GO_for_separate_G8_freeze": True,
                "this_result_does_not_authorize_G8_execution": True,
                "retry_authorized": False,
                "candidate_consumed": 0,
            },
        }
        result_evidence = publish_exclusive(
            artifacts_fd, RESULT.name, result, RESULT
        )
        print(
            json.dumps(
                {
                    "status": result["status"],
                    "result": result_evidence,
                    "aggregate_cache_sha256": result["cache"][
                        "aggregate_cache_sha256"
                    ],
                    "optimizer_steps": 0,
                    "candidate_consumed": 0,
                },
                ensure_ascii=False,
                sort_keys=True,
            )
        )
        return 0
    except BaseException as error:
        if attempt_evidence is None:
            raise
        unchanged = True
        try:
            for snapshot in snapshots.values():
                assert_snapshot_unchanged(snapshot)
            assert_directory_unchanged(root_directory)
            assert_directory_unchanged(artifacts_directory)
        except BaseException:
            unchanged = False
        failure = sanitized_failure(
            error,
            phase,
            attempt_evidence,
            snapshots["protocol"]["sha256"],
            snapshots["runner"]["sha256"],
            unchanged,
        )
        publish_exclusive(artifacts_fd, RESULT.name, failure, RESULT)
        print(
            json.dumps(
                {
                    "status": failure["status"],
                    "phase": phase,
                    "retry_authorized": False,
                    "raw_error_published": False,
                },
                sort_keys=True,
            ),
            file=sys.stderr,
        )
        return 1
    finally:
        if snapshots:
            release_snapshots(snapshots)
        release_directory(artifacts_directory)
        release_directory(root_directory)


if __name__ == "__main__":
    raise SystemExit(main())
